name: exception_templates

description: Parameterized exception and error templates for Dart. Enables
  throwing and catching exception/error objects that are defined by their type
  argument.

version: 0.2.1

homepage: https://github.com/simphotonics/exception_templates

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies: null

dev_dependencies:
  pedantic: ^1.11.0
  test: ^1.16.8
